---
title: "group6-infographic-plots"
author: "Group 6"
date: "2026-04-07"
output: html_document
---

```{r setup}

# install.packages("rlang", dependencies = TRUE, repos = "https://cloud.r-project.org")
# install.packages("readxl")
library(tidytext)
library(tidyverse)
library(readxl)

```



```{r data-setup}

nephrology_data <- read_excel("/cloud/project/nephrology-updated.xlsx", 
                              sheet = "Option 1",
                              col_names = c("bite_text", "title", "source_name", "post", "paid", "media", "domain", "sentiment", "published_date", "author_gender", "user_name", "richness", "post_category"),
                              skip = 1,
                              na = c("", "Unknown")
                              )

nephrology_data

```

```{r}

# Line Chart

# Shows number of posts by month
posts <- nephrology_data %>%
  # create a new column indicating the month each post was published in
  mutate(month = floor_date(published_date, "month")) %>%
  # get the number of posts by month and sentiment
  count(month, sentiment)

posts_filled <- posts %>%
  complete(
    month = seq(min(month), max(month), by = "month"),
    sentiment = c("Negative", "Neutral", "Positive"),
    fill = list(n = 0)
  )
posts_filled <- posts_filled %>%
  mutate(sentiment = factor(sentiment, levels = c("Positive", "Neutral", "Negative")))
  # create line chart
  ggplot(posts_filled, aes(x = month, y = n, color = sentiment, group = sentiment)) +
  # create lines, make them thick enough to see trends
  geom_line(aes(size = sentiment), alpha = 0.9) +
  # style points for each month, making it easier to see how many posts 
  # were published in each month
  geom_point(aes(size = sentiment), stroke = 1.5, fill = "white", shape = 21) +
  scale_size_manual(values = c("Negative" = 1.8, "Neutral" = 0.8, "Positive" = 0.8), guide = "none")+
  # consistent color scale,emphasizing negative sentiment
  scale_color_manual(values =c("Negative" = "deeppink3", "Neutral" = "gray60", "Positive" = "#D1D1D1")) +
  scale_y_continuous(breaks = seq(0, 10, by = 2), limits = c(0, 10)) +
  labs(
    # title explains that these concerns are still persisting
    title = "Persistence of Negative Patient Sentiments",
    subtitle = "Total volume of nephrology-related posts per month (2023-2024)",
    x = "",
    y = "Number of Posts",
    color = "Post Sentiment"
  ) +
  # professional theme
  theme_minimal() +
  # bold title and remove unnecessary grid lines
    theme(plot.title = element_text(face = "bold", size = 16),
          plot.subtitle = element_text(size = 11.5),
          panel.grid.minor = element_blank(),
          legend.position = "top",
          axis.text = element_text(size = 11),
          axis.title = element_text(size = 12),
          )

```


```{r}

top_posts <- nephrology_data %>% 
  group_by(post_category) %>%
  summarize(
    total_posts = n(),
    neg_posts = sum(sentiment == "Negative", na.rm = TRUE),
    .groups = "drop"
  ) %>%
  mutate(
    priority = if_else(neg_posts >= 5, "Priority", "Other")
  )

avg_neg_posts <- round(mean(top_posts$neg_posts), 0)

top_posts

# create bar chart
ggplot(top_posts, aes(x = reorder(post_category, neg_posts))) +
  geom_col(aes(y = total_posts), fill = "#E0E0E0", width = 0.7, alpha = 0.3) +
  geom_col(aes(y = neg_posts, fill = priority), width = 0.7) +
  scale_fill_manual(values = c("Priority" = "deeppink3", "Other" = "#D3D3D3")) +
  geom_hline(
    yintercept = avg_neg_posts, 
    color = "black",
    linetype = "dashed",
    linewidth = 0.5) +
  annotate("text", x = 2.5, y = avg_neg_posts + 1, label = "Avg. Negative Posts: 5", hjust = 0, size = 3, fontface = "italic") +
  coord_flip() +
  labs(
    # title explaining what the bar chart shows
    title = "Common Nephrology Patient Discussions",
    subtitle= "Categories ranked by number of negative posts vs. total posts",
    x = "",
    y = "Total Posts",
    fill = "Status"
  ) + 
  # professional theme
  theme_minimal() +
  theme(
    panel.grid.minor = element_blank(),
    # move legend to top for better flow
    legend.position = "hide",
    # bold title
    plot.title = element_text(size = 14, face = "bold"),
    axis.text.y = element_text(size = 12, face = "bold"),
    panel.grid.major.y = element_blank()
  )

```



```{r}

top_3 <- c("Disease Progression & Management", "Treatment Side Effects", "Clinical Literacy/Uncertainty")

# most common words in posts under each category
custom_stop_words <- bind_rows(stop_words, tibble(word = c("kidney", "iga", "igan", "nephropathy", "iganephropathy", "protein", "nephrologist",
  "i'm", "it's", "ve", "i’m", "i’d", "i'd", "i’ve", "don’t", "it’s", "doesn’t", "you're", "you’re", "can’t", "didn’t",
  "day", "days", "weeks", "months", "time", "bit", "taking", "recently", "condition", 
  "started", "people", "https", "appointments", "head", "solid", "told", "due", 
  "medication", "disease", "bad", "life", "feel", "controlling", "diagnosed", 
  "effects", "drug", "treatment", "treatments", "company", "age", "doctor",
  "lot", "fine", "ago", "starting", "lasting", "questions", "apply", "affect", 
  "org", "august", "multiple", "anymore"), lexicon = "custom"))

category_words <- nephrology_data %>%
  filter(post_category %in% top_3) %>%
  mutate(bite_text = str_to_lower(bite_text)) %>%
  unnest_tokens(word, bite_text) %>%
  anti_join(custom_stop_words) %>%
  filter(!str_detect(word, "^[0-9]+$"), str_length(word) > 1) %>%
  count(post_category, sentiment, word, sort = TRUE) %>%
  group_by(post_category) %>%
  slice_max(n, n = 10, with_ties = FALSE) %>%
  ungroup()

category_titles <- category_words %>%
  mutate(post_category = case_when(
    post_category == "Disease Progression & Management" ~ "Disease Management",
    post_category == "Clinical Literacy/Uncertainty" ~ "Clinical Uncertainty",
    TRUE ~ post_category
  ))

# patient voice charts
ggplot(category_titles, aes(x = reorder_within(word, n, post_category), y = n)) +
  geom_segment(aes(x = reorder_within(word, n, post_category), xend = reorder_within(word, n, post_category), y = 0, yend = n), 
               linewidth = 1, color = "grey80") +
  geom_point(aes(color = sentiment), size = 5) +
  scale_x_reordered() +
  scale_color_manual(values = c("Negative" = "deeppink3",
                                "Neutral" = "#B0B0B0",
                                "Positive" = "#4ECDC4")) +
  coord_flip() +
  facet_wrap(~post_category, scales = "free_y", ncol = 3) +
  labs(
    title = "Top Patient Concerns and Emotions",
    subtitle = "Top 10 most common words in each category",
    x = NULL,
    y = "Frequency of Mentions",
    color = "Sentiment"
  ) +
  theme_minimal() +
  theme(
    strip.text = element_text(face = "bold", size = 14, lineheight = 1.1),
    plot.subtitle = element_text(size = 14),
    axis.text.y = element_text(size = 12, face = "bold"),
    axis.text.x = element_text(size = 12),
    axis.title.x = element_text(size = 12, margin = margin(t = 10)),
    plot.title = element_text(size = 22, face = "bold"),
    panel.spacing = unit(1.2, "lines"), 
    panel.grid.major.y = element_blank(),
    legend.position = "top",
  )

```

